#!/bin/bash
# Get the directory of the script
script_directory=$(dirname $(realpath $0))
directory=$(dirname $script_directory)

# Source .envrc if it exists
if [ -f $directory/.envrc ]; then
  source $directory/.envrc
fi

$directory/.venv/bin/python $directory/src/bai.py "$@"
