#!/bin/bash
set -e
# Get the directory of the script
script_directory=$(dirname $(realpath $0))
directory=$(dirname $script_directory)

# Source secrets.sh if it exists
if [ -f $directory/secrets.sh ]; then
  source $directory/secrets.sh
fi

$directory/.venv/bin/python $directory/src/bai.py "$@"
