#!/bin/bash

# Interactive filter for JSON files using fzf and jq
# Adapted from https://dev.to/pbnj/fzf-jq-interactive-jq-15no

# The {q} string is replaced by the query string
# Then we pass args 2:... to jq
echo '' | fzf-tmux -p '80%' --print-query --preview "cat '${1}' | jq {q} ${@:2}"
